# volume
bindel = ,XF86AudioRaiseVolume, exec, swayosd-client --output-volume raise
bindel = ,XF86AudioLowerVolume, exec, swayosd-client --output-volume lower
bindel = ,XF86AudioMute, exec, swayosd-client --output-volume mute-toggle
bindel = ,XF86AudioMicMute, exec, swayosd-client --input-volume mute-toggle

# brightness (two binds per key)
bindel = ,XF86MonBrightnessUp, exec, brightnessctl set 5%+
bindel = ,XF86MonBrightnessUp, exec, swayosd-client --brightness raise

bindel = ,XF86MonBrightnessDown, exec, brightnessctl set 5%-
bindel = ,XF86MonBrightnessDown, exec, swayosd-client --brightness lower

# precise brightness
bindel = ALT, XF86MonBrightnessUp, exec, brightnessctl set 1%+
bindel = ALT, XF86MonBrightnessUp, exec, swayosd-client --brightness raise

bindel = ALT, XF86MonBrightnessDown, exec, brightnessctl set 1%-
bindel = ALT, XF86MonBrightnessDown, exec, swayosd-client --brightness lower
