[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\f/home/anurag)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0 \0\0\x2\x7f\0\0\x3\x1f\0\0\0\0\0\0\0 \0\0\x2\x7f\0\0\x3\x1f\0\0\0\0\0\0\0\0\x5\0\0\0\0\0\0\0\0 \0\0\x2\x7f\0\0\x3\x1f)

[FullScreen]
pos=@Point(240 738)
screen=@Rect(0 0 1280 800)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(640 687)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///home/anurag/Downloads/%5BAnime%20Time%5D%20Attack%20On%20Titan%20%28Complete%20Series%29%20%28S01-S04%2BOVA%29%20%5BDual%20Audio%5D%5BBD%5D%5B1080p%5D%5BHEVC%2010bit%20x265%5D%5BAAC%5D%5BEng%20Sub%5D/%5BAnime%20Time%5D%20Attack%20on%20titan%20%28Season%2001%29/%5BAnime%20Time%5D%20Attack%20On%20Titan%20-%2001.mkv, file:///home/anurag/Downloads/Hamnet.2025.bluray.sdr.1080p.av1.5.1.opus.subs.1900mb-Dust/Hamnet.2025.bluray.sdr.1080p.av1.5.1.opus.subs.1900mb-Dust.mkv
times=0, 0

[gototimedialog]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x2\x80\0\0\x1\x90\0\0\x3\xdb\0\0\x1\xda\0\0\x2\x80\0\0\x1\x90\0\0\x3\xdb\0\0\x1\xda\0\0\0\0\0\0\0\0\x5\0\0\0\x2\x80\0\0\x1\x90\0\0\x3\xdb\0\0\x1\xda)
