foreground #ffcead
background #060B1E
selection_foreground #060B1E
selection_background #ffcead

cursor #ffcead
cursor_text_color #060B1E
cursor_shape beam
cursor_blink_interval 0.4
cursor_stop_blinking_after 0
cursor_beam_thickness 2.0

active_border_color #7d82d9
active_tab_background #7d82d9

color0 #060B1E
color1 #ED5B5A
color2 #92a593
color3 #E9BB4F
color4 #7d82d9
color5 #c89dc1
color6 #a3bfd1
color7 #F99957
color8 #6d7db6
color9 #faaaa9
color10 #c4cfc4
color11 #f7dc9c
color12 #c2c4f0
color13 #ead7e7
color14 #dfeaf0
color15 #ffcead

# Font
font_family JetBrainsMono Nerd Font
bold_italic_font auto
font_size        11.0
bold_font JetBrainsMono Nerd Font Bold

# Window
window_padding_width 14
hide_window_decorations yes
confirm_os_window_close 0

# Keybindings
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

# Allow remote access
allow_remote_control yes

# Aesthetics
cursor_shape block
cursor_blink_interval 0
shell_integration no-cursor
enable_audio_bell no

# Minimal Tab bar styling
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
