exec-once = uwsm-app -- dunst
exec-once = uwsm-app -- waybar
exec-once = uwsm-app -- hypridle
exec-once = uwsm-app -- swayosd-server
exec-once = vicinae server
exec-once = systemctl --user enable --now hyprpolkitagent.service
exec-once = battery-alert
exec-once = uwsm-app -- swww-daemon
exec-once = uwsm-app -- sh -c "swww-daemon & while ! swww query; do sleep 0.1; done; swww img /home/anurag/Pictures/wall.jpg"
