general {
    lock_cmd = hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on; hyprlock
}

listener {
    timeout = 180
    on-timeout = loginctl lock-session
}

listener {
    timeout = 240
    on-timeout = sleep 1 && hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 600
    on-timeout = sleep 2 && systemctl suspend
}
